#validar
name: Validar HTML y CSS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'

      - name: Instalar HTML Validate
        run: npm install -g html-validate

      - name: Validar HTML con html-validate
        run: html-validate "**/*.html"

      - name: Instalar CSS Lint
        run: npm install -g csslint

      - name: Validar todos los CSS con CSS Lint
        run: |
          for file in $(find . -name "*.css"); do
            echo "Validando $file..."
            csslint "$file" || true
          done
      
